name: lords_arena
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  logger: ^2.0.2
  flutter_localizations:
    sdk: flutter
  test_cov_console: ^0.2.2
  bloc_test: ^10.0.0
  flame: ^1.30.1
  flame_audio: ^2.11.8
  shared_preferences: ^2.2.2
  vibration: ^3.1.3
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/LordsArena.png
    - assets/images/warzone.jpg
    - assets/images/splash.png
    - assets/images/kp.png
    - assets/images/sher.png
    - assets/images/prachanda.png
    - assets/images/bullet.png
    - assets/images/fire_bullet.png
    - assets/images/poison_bullet.png
    - assets/images/enemy_bullet.png
    - assets/images/explosion_sheet.png
    - assets/images/icon.png
    - assets/audio/bg.mp3
    - assets/audio/hit.wav
    - assets/audio/shoot.wav
    - assets/audio/explosion.wav
  
  fonts:
    - family: Tinos
      fonts:
        - asset: assets/fonts/Tinos-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tinos-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tinos-Italic.ttf
          style: italic
        - asset: assets/fonts/Tinos-BoldItalic.ttf
          style: italic
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#0D1B1E"
    theme_color: "#FFA500"