name: lords_arena
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  logger: ^2.0.2
  flutter_localizations:
    sdk: flutter
  test_cov_console: ^0.2.2
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/LordsArena.png
    - assets/images/warzone.jpg
    - assets/images/splash.png

  fonts:
    - family: Tinos
      fonts:
        - asset: assets/fonts/Tinos-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tinos-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tinos-Italic.ttf
          style: italic
